In [2]:
import numpy as np

In [2]:
test_array = np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [3]:
test_array[3]

8.0

In [4]:
type(test_array[3])

numpy.float64

In [6]:
print(test_array.dtype)

float64


In [7]:
print(test_array.shape)

(4,)


In [1]:
import sys

In [4]:
##1/22일  numpy array

In [5]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)

In [8]:
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [9]:
x[1,1:3]

array([7, 8])

In [10]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [14]:
x= np.array(range(15),int).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [16]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [17]:
## np.arange //기존의 range와 다르게 실수형의 배열이 가능

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [20]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
np.ones(shape=(5,2),dtype=np.int8)## ones 는 1값

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [25]:
np.zeros(shape=(2,2),dtype=np.float32) ## zeros는 0

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [24]:
np.empty(shape=(2,4),dtype=np.float32) ##empty는 의미없는 num을 추가

array([[0.0000000e+00, 0.0000000e+00, 4.0810118e-29, 7.6651026e-43],
       [4.0804100e-29, 7.6651026e-43, 4.0804341e-29, 7.6651026e-43]],
      dtype=float32)

In [33]:

x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
## 기본의 넘파이배열에 같은크기를 만들고 값을 1로 대체
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
## 기본의 넘파이배열에 같은크기를 만들고 값을 0로 대체
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
##단위행렬을 생성(identity,eye,diag)
np.identity(n=3,dtype=np.int8)
np.identity(n=4,dtype=np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [46]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.diag(matrix)

array([0, 4, 8])

In [54]:
np.diag(matrix, k=0)

array([0, 4, 8])

In [57]:
#통계분석 함수
##uniform 함수 : 균등분포 함수
np.random.uniform(0,5,10)

array([1.78194812, 2.14358001, 0.92758677, 1.89383471, 3.2538002 ,
       4.90187775, 3.99472358, 1.87159664, 1.22983701, 4.73358503])

In [58]:
##normal 함수 : 정규분포 함수
np.random.normal(0,2,10)

array([-0.39228186, -1.08488767,  1.02197625,  0.93713423,  1.52748885,
       -2.2087977 , -0.64642535,  0.65706448, -4.7622365 ,  0.7721623 ])

In [59]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [61]:
test_array.sum(axis=1)

array([10, 26, 42])

In [63]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [64]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [65]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [66]:
third_order_tensor.sum(axis =2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [67]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [69]:
test_array.std()

3.452052529534663

In [70]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [71]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [72]:
#연결함수 // 두 객체 간의 결합을 지원하는 함수
## vstack,hstack


In [74]:
v1 =np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [76]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [77]:
v2

array([[4],
       [5],
       [6]])

In [78]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
v1=np.array([1,2,3,4]).reshape(2,2)
v2=np.array([[5,6]]).reshape(2,1)
v1

array([[1, 2],
       [3, 4]])

In [86]:
v2

array([[5],
       [6]])

In [87]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [96]:
v2=v2.reshape(1,2)
v2
np.concatenate((v1,v2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
##사칙연산 함수

In [98]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [101]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [103]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [104]:
#dot함수 : 벡터의 내적 연산
x_1 = np.arange(1,7).reshape(2,3)
x_2= np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [107]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [109]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [110]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [111]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [112]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [113]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [114]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [115]:
x = np.array([4,3,2,6,8,5])
x>3

array([ True, False, False,  True,  True,  True])

In [116]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x>y

array([False,  True, False])

#비교연산과 데이터 추출

In [117]:
x = np.array([4,6,7,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [121]:
(x>3).all()##전부다 참이여야 True

False

In [120]:
(x>3).any()##하나만 참이면 True

True

In [122]:
x= np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [124]:
np.where(x>5)##boolean 형태로 참값의 인덱스를 변환

(array([1, 2], dtype=int64),)

In [125]:
x = np.array([4,6,7,3,2])
np.where(x>5,10,20)

array([20, 10, 10, 20, 20])

In [127]:
cond = x>3
x[cond]

array([4, 6, 7])

In [128]:
x.shape

(5,)

In [129]:
cond.shape

(5,)

## 팬시 인덱스
정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환

In [130]:
x=np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [131]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [132]:
x = np.array([[1,4],[9,16]],int)
a = np.array([0,1,1,1,0,0],int)
b = np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])